#!/usr/bin/perl

use strict;
use lib 'lib';
use Cwd;
use ShipIt;

my $dir = shift || getcwd;
die "Usage: shipit [<dir>]\n" unless -d $dir;
chdir($dir) or die "Failed to chdir to $dir\n";
die "No .shipit configuration file in $dir\n" unless -e ".shipit";

my $conf  = ShipIt::Conf->parse(".shipit");
my $state = ShipIt::State->new($conf);

foreach my $step ($conf->steps) {
    warn "Running step $step\n";
    $step->run($state);
}
